// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq04mmv419uIZieiLfV8BDKUqYKbqSX88',
    appId: '1:271474221388:web:de356574cefcd52c48afe9',
    messagingSenderId: '271474221388',
    projectId: 'eggy-testing',
    authDomain: 'eggy-testing.firebaseapp.com',
    storageBucket: 'eggy-testing.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATVeXR5kgvvoWYC7E3FBO0gLX9Eipo9Zo',
    appId: '1:271474221388:android:c9e3c2735d7d1a9f48afe9',
    messagingSenderId: '271474221388',
    projectId: 'eggy-testing',
    storageBucket: 'eggy-testing.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaMt1IXNyKTncP36NmVuleW4eGsFYJuZ0',
    appId: '1:271474221388:ios:85d2029ed9eced3c48afe9',
    messagingSenderId: '271474221388',
    projectId: 'eggy-testing',
    storageBucket: 'eggy-testing.appspot.com',
    iosBundleId: 'com.example.pethandyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaMt1IXNyKTncP36NmVuleW4eGsFYJuZ0',
    appId: '1:271474221388:ios:d51d73b0eae84c1848afe9',
    messagingSenderId: '271474221388',
    projectId: 'eggy-testing',
    storageBucket: 'eggy-testing.appspot.com',
    iosBundleId: 'com.example.pethandyApp.RunnerTests',
  );
}
